service: perplexity-search-api
frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.10
  architecture: arm64
  region: us-east-1
  ecr:
    images:
      perplexity_image:
        path: ./
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - bedrock:InvokeAgent
          Resource:
            - arn:aws:bedrock:us-east-1:*:agent-alias/CIARP5VKY3/TSTALIASID

functions:
  perplexity_search:
    image:
      name: perplexity_image
      command:
        - handler.perplexity_search
    timeout: 30
    events:
      - httpApi:
          path: /search-perplexity
          method: post

  perplexity_chat:
    image:
      name: perplexity_image
      command:
        - handler.perplexity_chat
    timeout: 30
    events:
      - httpApi:
          path: /chat-perplexity
          method: post

  firecrawl_batch_scrape:
    image:
      name: perplexity_image
      command:
        - handler.firecrawl_batch_scrape
    timeout: 30
    events:
      - httpApi:
          path: /batch-scrape
          method: post

  firecrawl_batch_status:
    image:
      name: perplexity_image
      command:
        - handler.firecrawl_batch_status
    timeout: 30
    events:
      - httpApi:
          path: /batch-scrape-status
          method: post

  bedrock_chat:
    image:
      name: perplexity_image
      command:
        - handler.bedrock_chat
    timeout: 30
    events:
      - httpApi:
          path: /bedrock-chat
          method: post
